### ISSUE TITLE
[Bug] Canceling the stream takes user to an empty profile page

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodCollective#116]
Canceling a stream does not mean that the donations made so far were withdrawed, so the profile should not show empty.

<img width="1065" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b5efbf5db8a41a033cecd69609f3e02748a3232/Screen%20Shot%202024-01-18%20at%2009.54.49.png" alt="Screen Shot 2024-01-18 at 09.54.49.png" />

**Comment by krisbitney** [comment]
The donations aren't being removed. I think the wallet is empty due to this error that is preventing subgraph queries:

<img width="558" alt="Screenshot 2024-01-19 at 12 52 30 PM" src="https://github.com/GoodDollar/GoodCollective/assets/39842820/fef98d5d-7ede-453b-828c-9ea0bf112705">

@sirpy @L03TJ3 I don't have access to the subgraph infra. Would you be able to take a look and see what's going on?

**Comment by sirpy** [comment]
@krisbitney thegraph is a free service, we dont have any special access. Does this still happen?

**Comment by krisbitney** [comment]
> @krisbitney thegraph is a free service, we dont have any special access. Does this still happen?

I'm no longer getting this error. Maybe it happened because I had recently redeployed the subgraph multiple times and we were rate limited, or maybe The Graph was having some issues on their end. I don't know.

@patpedrosa Could you please try again? I just tested it and my donation still showed. 

I actually had the opposite problem: it took a few minutes before my profile reflected that the donation had stopped, so it looked like the donation kept flowing. My total donated amount went up to $GD 134, then reverted back to 132. The donation fetching is polled with an interval of 1 second (i.e. it checks for new data every 1 second), but it takes a short time for the transaction to finalize and the subgraph to update.

**Comment by krisbitney** [comment]
> I've retested it, it's showing correctly. Thank you.

Thank you for taking another look. I appreciate it!
