### ISSUE TITLE
[BUG] Steward Wallet Page - Actions should link to NFTs

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#127]
User should be able to click "x action" and be brought to an Activity Log listing that is a summary of the NFT(s) that triggered the action.

Example of an NFT that results in a payment action: https://celoscan.io/address/0x52484d481b11fe639c55bbf139702b238ef8ff64

**Comment by decentralauren** [comment]
@L03TJ3 please share a suggested quick fix here :)

**Comment by L03TJ3** [comment]
Full fix:
- [ ] - Should lead to the now mock-up page Activity and show a list of the nfts
- [ ] - the nft items on the list should lead to the nft's explorer page

Quick fix:
- [ ] - Clicking on action should lead to the explorer.
- [ ] - the url to use should lead to the advanced-fliter page with url params so that only a list of goodcollective NFT's are shown

**Comment by decentralauren** [comment]
@L03TJ3 is this ready to assign to Kris?

**Comment by L03TJ3** [comment]
@decentralauren not sure yet as there might be an issue on contract level

There is conversation on tg regarding this

**Comment by L03TJ3** [comment]
Still up into research as I am not able to mint a new nft yet. awaiting @sirpy assistance

@decentralauren so I guess this will be staying our own issue to tackle
