### ISSUE TITLE
[Bug] Total Donations Received should display total donations received#527

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodCollective#152]
"Total donations received" should be a sum of "Total Paid out" and "Current Pool." In the example screen shot the total amount should be 611,007.95

![Screenshot 2024-02-01 at 12 10 39 PM](https://github.com/GoodDollar/GoodCollective/assets/149098646/5916b1ef-e0a9-4880-8a2d-bcf92fdbfbaf)

**Comment by krisbitney** [comment]
@decentralauren That particular pool received 600,000 G$ in a transfer. 

See: https://explorer.celo.org/mainnet/tx/0x2d7ab81d80cecc3aacc4ee7ceb5628288db2298e4ac756b79cc4228b0fa61838

Multiple other pools also have extra G$ transfers.

I was also originally using `supportSingleBatch` instead of `supportSingleTransferAndCall`. The `supportSingleBatch` method has a hidden fee that I didn't know about until today. 

I have donated G$ 310 to this collective. G$100 was donated using `supportSingleTransferAndCall`, while the remaining G$210 was donated using `supportSingleBatch`. Notice that there is a fee of exactly 10% for using `supportSingleBatch`. The `Current Pool` amount is only G$ 279. But the fee is not reflected in the Total Donations Received because it is not deducted from the supporter's contribution amount in the smart contract.
https://explorer.celo.org/mainnet/address/0xF0E351a9B7C0e89340F543B377f9Ac7810fF7Fa0/token-transfers#address-tabs

**Comment by decentralauren** [comment]
OK @krisbitney thank for clarifying - so it sounds like the 2 issues are:
- current UI only shows pool contributions made in the UI
- Pools have transaction fees that are not shown here

Can you please update the Total Donations Received to indeed show total cumulative amount donated to the pool (as designed)? We will need to open a ticket (assigned to us) for to show the fees paid out from the pool.

**Comment by krisbitney** [comment]
Yes, I can use the sum of `Current Pool` and `Total Paid Out`. This would be the total G$ the pool contract received for any reason. The total donations listed in places like the "See All Donors" page will not sum to the same amount.

**Comment by decentralauren** [comment]
Thanks @krisbitney This is great.

> The total donations listed in places like the "See All Donors" page will not sum to the same amount.

This would only show donations made through the interface, then? Why would it not show any donations made to the contract?

**Comment by krisbitney** [comment]
> Thanks @krisbitney This is great.
> 
> > The total donations listed in places like the "See All Donors" page will not sum to the same amount.
> 
> This would only show donations made through the interface, then? Why would it not show any donations made to the contract?

This thread is the first time it has been mentioned that you want to count all token transfers to a smart contract as donations, rather than the donations explicitly tracked by the smart contracts and Subgraph database. As a result, the UI is set up to integrate the smart contracts and Subgraph database directly.

Reworking the database integration and supplementing it with a mechanism to track the sources of all transfers to the smart contract is not a trivial task.

You suggested before that I didn't implement the "Total Donations Received" feature "as designed". Could you please point me to the design? When I look at the project requirements, I don't see the property mentioned. And I don't see notes about it in the Figma.

**Comment by krisbitney** [comment]
This PR replaces the sum of individual donations with the sum of "Total Paid Out" and "Current Pool": https://github.com/GoodDollar/GoodCollective/pull/160

**Comment by decentralauren** [comment]
@krisbitney - thank you for clarifying why this was implemented this way. There was unfortunately never a discussion (that I am aware of) or question about whether this value should be called from the UI or directly from the contract. In our initial walkthrough we asked that all values possible should be read directly from the contract. It seems that this may have been lost or not clearly conveyed in the game of telephone.

I'm referring to the requirements that were shared via the Figma, which clearly shows the total donations as the sum of the two numbers below![image](https://github.com/GoodDollar/GoodCollective/assets/149098646/01d97235-3973-4a50-b6bd-e56af576735b)

**Comment by krisbitney** [comment]
To clarify, all of the values come from the contracts. The UI sends events to the contracts, through transactions. The Subgraph database reads events from the contracts. The UI reads data from the Subgraph.

Write: UI --> contracts
Read: contracts --> subgraph --> UI

But it is important to realize that someone can send tokens of any kind to the pool contracts without calling the smart contract functions that cause the contract to document the token transfer as a donation.

The reason the numbers don't sum nicely in the UI is because the "Total Donations Received" was being calculated by summing all of the donations known to the smart contract. But the smart contract doesn't track every token transfer. Token transfers can happen without interacting with the pool's smart contract.

I see that the numbers sum nicely in the Figma design, but that does not imply that they always would with real data. I assumed the "Total Donations Received" should correspond to your smart contract's own data, for which we created the Subgraph database.

**Comment by vldkhh** [comment]
@krisbitney please apply fonts to this 
![Snag_3612b40e](https://github.com/GoodDollar/GoodCollective/assets/107620432/a26ea536-5cab-4f44-b183-2e0009974204)

@decentralauren @patpedrosa looks like the numbers are correct

**Comment by krisbitney** [comment]
> @krisbitney please apply fonts to this ![Snag_3612b40e](https://private-user-images.githubusercontent.com/107620432/302450516-a26ea536-5cab-4f44-b183-2e0009974204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDM1ODAsIm5iZiI6MTcwNzIwMzI4MCwicGF0aCI6Ii8xMDc2MjA0MzIvMzAyNDUwNTE2LWEyNmVhNTM2LTVjYWItNGY0NC1iMTgzLTJlMDAwOTk3NDIwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwNzA4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjI5MjFiYjkxYjc1NzcwYWQ1YjFmYzA2OTIwY2ZjOGM4OWJjOTk5MmNmYTk1YzYyZTc2NTM5MWFhNDA3MTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h_EVDX3y1fPHLYL4kW_CChFR8zPcWk6n9gs8bgc6tGg)
> 
> @decentralauren @patpedrosa looks like the numbers are correct

I'm fixing it now. I'm not sure what changed in the fonts. Super weird!

**Comment by krisbitney** [comment]
Fixed here: https://github.com/GoodDollar/GoodCollective/pull/171

**Comment by vldkhh** [comment]
verified
