### ISSUE TITLE
[BUG, GoodCollective]  Wallet balance should just show 2 values after the decimal (IE 61.31 G$)

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#250]
Wallet balance should just show 2 values after the decimal (IE 61.31 G$) 

https://gooddollar.slack.com/archives/C07RRC4NQTY/p1733766014668339

![image](https://github.com/user-attachments/assets/d80e8af8-ab41-46a1-b77b-7bab5226cb8b)

**Comment by Chrisatom** [comment]
Hi @vldkhh,
I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by sirpy** [comment]
fixed 657505ef22ab630c97cf268b1ebad8a068993362

**Comment by vldkhh** [comment]
verified on dev

**Comment by vldkhh** [comment]
verified on prod
