### ISSUE TITLE
[Design QA] Page padding/Mobile

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#32]
All pages padding should be set to 16px (from right and left)
right now some pages, or at least part of the page is set to 24px.. it’s a waste of space.

Devs:
<img width="379" alt="Screen Shot 2023-11-14 at 12 47 08" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/7c50d1a5-567c-47d0-89b0-26cb698a871d">

Design:
<img width="418" alt="Screen Shot 2023-11-15 at 11 36 33" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/e8cf8677-aced-4460-815e-82b8c92097f4">

**Comment by benefacto** [comment]
## Technical Implementation

To standardize the padding across all pages to 16px (from right and left) in your React Native code, you'll need to adjust the styles applied to the main containers of your pages. Here's how you can modify the `WalletProfile` component and apply a similar approach to other components as needed:

1. **Update the Main Container Style:**
   Adjust the `container` style in your stylesheet to ensure it has 16px padding on the right and left. This seems to be already done in your code, but it's important to ensure consistency across all components.

   ```javascript
   container: {
     width: '100%',
     padding: 16, // Set padding to 16px
     backgroundColor: Colors.white,
   },
   ```

2. **Review Other Styles:**
   Check other style properties in your stylesheet to ensure no other elements are overriding this padding with a different value (like 24px). Specifically, look for any padding or margin properties in the stylesheet and update them accordingly.

3. **Apply Changes to Other Components:**
   Since you want this change to be reflected across all pages, you'll need to ensure that similar adjustments are made to the main container styles of other components/pages in your application.

4. **Verify Nested Components:**
   If there are nested components within each page, ensure that their styles don't inadvertently increase the overall padding or margin beyond the desired 16px.

5. **Test on Different Devices:**
   After making these changes, it's crucial to test your application on different devices (or screen sizes) to ensure that the UI looks consistent and the 16px padding is maintained across all pages.

6. **Ensure Responsiveness:**
   Since you're working with both desktop and mobile layouts, make sure that the responsiveness of your application is not affected by these changes.

By following these steps, you'll be able to set a consistent padding of 16px from right and left across all pages in your application, ensuring a uniform look and feel. Remember, the key here is consistency and thorough testing across different components and screen sizes.
