### ISSUE TITLE
[Design QA] View Collective Page - icon alignment / Mobile + Desktop

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#34]
icons and text should have center alignment 

Devs: 
<img width="374" alt="Screen Shot 2023-11-15 at 11 42 15" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/6e0b8472-b858-4e7b-ab9e-e6e469c96cc6">

Design:
<img width="373" alt="Screen Shot 2023-11-15 at 11 41 50" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/d87877af-bba3-4912-9cc7-96c937e1fe2e">

**Comment by benefacto** [comment]
## Technical Implementation

To align icons and text to the center in the `ViewCollective` component, you need to adjust the styles of the elements containing the icons and text. Here's a step-by-step guide on how to modify the code:

1. **Update Icon and Text Container Styles:**
   For every container that holds an icon and a text, ensure that its style promotes center alignment. This can be achieved with `alignItems: 'center'` and `justifyContent: 'center'` properties for a flex container.

   Update the styles for `collectiveDetailsMobile`, `icons`, and any other relevant container:

   ```javascript
   collectiveDetailsMobile: {
     flexDirection: 'row',
     alignItems: 'center', // Center items vertically in the row
     justifyContent: 'center', // Center items horizontally
     gap: 8,
   },

   icons: {
     marginTop: 5,
     flexDirection: 'row',
     alignSelf: 'center',
     alignItems: 'center', // Add this for vertical alignment
     justifyContent: 'space-between', // If you want even spacing between icons
     gap: 24,
   },
   ```

2. **Text Alignment:**
   For text elements, ensure that the `textAlign` property is set to 'center' if you want the text itself to be centered within its container.

   ```javascript
   title: {
     ...InterSemiBold,
     fontSize: 20,
     color: Colors.black,
     textAlign: 'center', // Center align text
   },

   informationLabel: {
     ...InterSemiBold,
     fontSize: 14,
     color: Colors.black,
     marginBottom: 16,
     textAlign: 'center', // Center align text
   },
   ```

3. **Check RowItem Component:**
   If the `RowItem` component is used for rendering items with icons and text, ensure it also supports center alignment. You might need to update the styles within the `RowItem` component as well.

4. **Ensure Consistency Across Resolutions:**
   Since you have different styles for desktop and mobile (`collectiveDesktopData`, `collectiveDetailsMobile`), make sure the alignment is consistent across both.

5. **Test the Changes:**
   After making these changes, test your application on different devices or screen sizes to ensure that the icons and text are properly aligned and the layout appears as expected.

By following these steps, you'll be able to ensure that icons and text in the `ViewCollective` component are centered according to the design requirements. Remember to check all related components and styles to maintain consistency throughout the application.

**Comment by vldkhh** [comment]
verified on web and mobile
