### ISSUE TITLE
[Design QA] View Collective page/ Mobile - Padding / Gap

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#35]
There’s a gap (the grey area) between the image and the text section, please delete it.

devs:
<img width="379" alt="Screen Shot 2023-11-14 at 13 14 25" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/9b1818b9-4d92-47c3-86cc-af96951f3986">

design:
<img width="377" alt="Screen Shot 2023-11-15 at 11 53 43" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/adbb3afd-00c6-44af-948f-a9ac830db588">

**Comment by benefacto** [comment]
## Technical Implementation

To remove the gap between the image and the text section in the `ViewCollective` component on mobile screens, you should adjust the relevant styles in your stylesheet. This gap is likely caused by either margin or padding settings in the styles for the image or the text container. Here's how to adjust the code:

1. **Identify the Elements Creating the Gap:**
   The gap is likely between the `image` and the `collectiveInformation` elements. Examine these styles to identify any margins or paddings that might be creating the gap.

2. **Adjust Image Style:**
   If the image style has a `marginBottom` or the `collectiveInformation` style has a `marginTop`, these could be creating the gap. Set them to 0 or reduce them as needed. 

   ```javascript
   image: {
     width: '100%',
     height: 192,
     marginBottom: 0, // Set marginBottom to 0 or reduce it
   },
   ```

3. **Adjust Collective Information Style:**
   Similarly, adjust the style for the `collectiveInformation` element:

   ```javascript
   collectiveInformation: {
     flex: 1,
     flexDirection: 'row',
     gap: 8,
     marginTop: 0, // Set marginTop to 0 or reduce it
   },
   ```

4. **Check for Additional Padding or Margin:**
   There might be additional padding or margin applied to the parent container or within the `collectiveDetailsMobile` or `collectiveDesktopData` styles. Check these and adjust as necessary.

5. **Test on Mobile Screen:**
   After making these changes, test your application on a mobile screen to ensure the gap is removed and the layout appears as expected.

6. **Ensure Responsiveness:**
   Ensure that these changes don't adversely affect the layout on larger screens or desktop resolution. You might need to use media queries or platform-specific styles if the layout significantly differs between mobile and desktop.

By following these steps, you should be able to remove the unwanted gap between the image and the text section on mobile screens in your `ViewCollective` component. Remember to test on various screen sizes to ensure the changes work across different devices.

**Comment by vldkhh** [comment]
verified on web and mobile
