### ISSUE TITLE
[Design QA] Stewards Page/Mobile - Padding & Margins

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#36]
- here’s a gap between the image and the top nav bar, please delete it.

- the title white background should only have rounded corners in the bottom part

- there’s a margin on the right side of the screen, please delete it.

- there’s a vertical padding in the bottom of the screen under See Your Impact button, delete it, should be set to 0.

Devs:
<img width="377" alt="Screen Shot 2023-11-15 at 11 56 46" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/46a644e7-203b-422d-93d6-d293e02f788b">

Design:
<img width="377" alt="Screen Shot 2023-11-15 at 11 57 19" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/70fb22d2-7784-4e5e-9724-8278d595ec94">

**Comment by benefacto** [comment]
## Technical Implementation 

To address the four layout concerns in your `ViewCollective` component, you'll need to adjust the relevant styles. Here's how to modify each point:

1. **Remove Gap Between Image and Top Nav Bar:**
   The gap is likely due to margin or padding around the `image` or its container. Set the margin to 0 to remove this space.

   ```javascript
   image: {
     width: '100%',
     height: 192,
     marginTop: 0, // Remove top margin
     // Other styles...
   },
   ```

2. **Rounded Corners Only at the Bottom of Title's White Background:**
   To achieve rounded corners only at the bottom, set the `borderRadius` property only for the bottom corners.

   ```javascript
   title: {
     ...InterSemiBold,
     fontSize: 20,
     color: Colors.black,
     borderRadius: 0,
     borderBottomLeftRadius: 10, // Rounded bottom-left corner
     borderBottomRightRadius: 10, // Rounded bottom-right corner
     // Other styles...
   },
   ```

3. **Remove Right Margin of the Screen:**
   Ensure that the main container of your component doesn't have any unnecessary right margin or padding.

   ```javascript
   container: {
     width: '100%',
     padding: 24,
     paddingRight: 0, // Remove right padding
     // Other styles...
   },
   ```

4. **Set Bottom Padding to 0 Under 'See Your Impact' Button:**
   If the bottom padding is part of the `container` or a specific section that includes the button, set its bottom padding to 0.

   ```javascript
   collectiveDonateBox: {
     gap: 24,
     paddingBottom: 0, // Set bottom padding to 0
     // Other styles...
   },
   ```

After making these adjustments, test your application on various screen sizes to ensure that the layout changes appear as expected. It's important to verify that these changes don't negatively affect the layout on other screens or resolutions.
