### ISSUE TITLE
[Design QA] Donation page/Desktop - CTA Button Size

### ISSUE THREAD

**Issue by SanaJamm** [GoodDollar/GoodCollective#39]
Set Confirm button to 343px wide and not fill whole screen.

Devs:
<img width="1728" alt="Screen Shot 2023-11-16 at 10 47 29" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/53854b51-a9a0-43be-9d95-5ed2fe75491c">

Design:
<img width="755" alt="Screen Shot 2023-11-16 at 10 48 45" src="https://github.com/GoodDollar/GoodCollective/assets/122018139/5bc8aca3-6a64-42a1-bc0e-e9b68222b26f">

**Comment by benefacto** [comment]
## Technical Implementation

To set the width of the "Confirm" button to 343px and prevent it from filling the whole screen in your `DonateComponent`, you need to adjust the styles applied to the `RoundedButton` component. This can be done by updating the `RoundedButton` styling in your `styles` object.

Here is how you can do it:

1. **Define a New Style for the Button:**
   Create a new style in your `StyleSheet` that sets the width of the button to 343px.

   ```javascript
   const styles = StyleSheet.create({
     // ... other styles ...
     confirmButton: {
       width: 343, // Set the width to 343px
       alignSelf: 'center', // Center the button
       // Add any other styling as needed
     },
     // ... other styles ...
   });
   ```

2. **Apply the Style to the RoundedButton:**
   Use the new style when rendering the `RoundedButton`. Since `RoundedButton` might be a custom component, ensure it accepts and applies the passed style correctly.

   ```javascript
   <RoundedButton
     title="Confirm"
     // ... other props ...
     style={styles.confirmButton} // Apply the new style
   />
   ```

3. **Responsive Design Consideration:**
   If the button should have a different width on different screen sizes (like mobile vs desktop), you can use `useMediaQuery` to conditionally apply styles.

   ```javascript
   const [isDesktopResolution] = useMediaQuery({
     minWidth: 612,
   });

   // In the render section
   <RoundedButton
     title="Confirm"
     // ... other props ...
     style={isDesktopResolution ? styles.confirmButtonDesktop : styles.confirmButton}
   />
   ```

   Define `styles.confirmButtonDesktop` in your `StyleSheet` for the desktop view if needed.

4. **Test on Various Devices:**
   After applying these changes, test the button on different devices and screen sizes to ensure that the button appears correctly and is consistently 343px wide.

By following these steps, you should be able to set the width of the "Confirm" button to 343px and align it properly within your `DonateComponent`. Remember to check if other elements or styles might be affecting the button's layout and adjust them as necessary.

**Comment by krisbitney** [comment]
@SanaJamm I notice that the "Review your donation" box and the text below it are not in the desktop design, but they are currently present in the app. Which is correct?

**Comment by SanaJamm** [comment]
@krisbitney the mobile one is the correct one
