### ISSUE TITLE
[Mobile/IOS/BUG/UX] Connect button shows Metamask after tapping on Wallet Connect

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodCollective#90]
This button is not in line with the Figma design specs. It also shows metamask right after tapping on wallet connect.

Build:
![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/72bab36f-dd93-4eaa-9e71-c6727b146769)

Design:
![image](https://github.com/GoodDollar/GoodCollective/assets/6606028/f2535754-54d6-42b9-aced-fba74ffaa0fd)

- [ ] - should not show metamask when clicking on wallet-connect

**Comment by decentralauren** [comment]
@sanajamm @patpedrosa I thought we had different designs for mobile vs desktop (per an earlier discussion).  If so can you please be more clear of which one is supposed to show here and why?

**Comment by krisbitney** [comment]
@decentralauren @vldkhh I believe this is completed

**Comment by krisbitney** [comment]
@vldkhh Okay, I think I misunderstood this request before when the pics weren't loading. You are saying you want the WalletConnect logo to appear on the `Connect Wallet` button? In at least one of the Figma design items, the logo is not there.

I think maybe there was some confusion because the `Connect Wallet` button provides the option to connect with WalletConnect or MetaMask. After you connect your wallet, the `Connect Wallet` button is no longer visible.

Could you please clarify exactly how this is supposed to look and behave? Under what condition should the WalletConnect logo be added to the button text?

**Comment by krisbitney** [comment]
When I "fixed" this before, I thought you were just saying the order in which MetaMask and WalletConnect appeared in the menu was wrong. So I switched their places.

**Comment by L03TJ3** [comment]
@krisbitney MetaMask is not an option on mobile as an injected provider.
so just to clarify the request is/was to only show wallet-connect on mobile, indicated with a wallet-connect icon in the button

**Comment by krisbitney** [comment]
Okay. This is what is in the Figma. Can you please clarify: if the mobile button only supports WalletConnect, do you still want a dropdown menu to open or do you want a button click to immediately try to use WalletConnect?

<img width="508" alt="Screenshot 2024-01-30 at 12 22 14 PM" src="https://github.com/GoodDollar/GoodCollective/assets/39842820/4b09c443-66c0-48f3-8377-ba229ae4ea9a">

**Comment by L03TJ3** [comment]
@patpedrosa Think we can just do with a button click no dropdown right?

**Comment by krisbitney** [comment]
@L03TJ3 @patpedrosa @vldkhh This PR adds the WalletConnect logo and removes the dropdown on mobile: https://github.com/GoodDollar/GoodCollective/pull/131

**Comment by krisbitney** [comment]
@vldkhh Could you please review this again now that the PR is merged?

**Comment by vldkhh** [comment]
@krisbitney looks like it fixed 
![img_3510_720](https://github.com/GoodDollar/GoodCollective/assets/107620432/a5296b2e-e9cf-4db6-bc81-04c0878da8b8)
